# This is a basic workflow to help you get started with Actions

name: Push to docker hub

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Variables used  
    env:
      image_name: creativitykills/nginx-php-server:latest
      DOCKER_ID: ${{ secrets.DOCKER_ID }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # build docker image with a tag
    - name: build docker image
      run: |
        docker build -t $image_name .
    
    # login to docker hub 
    - name: login to docker hub  
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    # push image to docker hub
    - name: push to docker
      run: docker push $image_name
      
